baseURL: https://thejimmynowak.github.io/
languageCode: pl-pl

params:
 homeInfoParams:
  Title: Blog
  Content: Radio, podróże i komputery
 
 socialIcons:
  - name: "Github"
    url: "https://github.com/thejimmynowak"
  - name: "Linkedin"
    url: "https://www.linkedin.com/in/datamikolaj/"
  - name: "qrz.com"
    url: "https://www.qrz.com/db/SP8UWU"
 defaultTheme: dark
 contact:
  email: datamikolaj@protonmail.com

menu:
 main:
  - identifier: Kontakt
    name: Kontakt
    url: /kontakt/
    weight: 10
title: TheJimmyNowak
theme: ["PaperMod"]
